# -*- coding: utf-8 -*-
"""Exam Introduction to Pyhton_Rob Kooij_i6259624

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RheBu9_53cMvmjwEDzlVeiDBLKDocWgW
"""

#1 Introduction (5pt)
#2 Data preparation: (20 pt)
#3 Explore and clean the data by: (20 pt)
#4 Describe and visualise: (50 pt)
#5 Conclusion (5pt)

#1 Introduction: Formulate a research question that allows for explorations and comparisons.
#The research question:
#Has The Netherlands compared to other Western Europe countrys less deaths? And is there a corralation with vaccinated people?

#2 Data preparation: The dataset of COVID
# pandas module for working with Series and Dataframes
import pandas as pd

# load dataset
covid = pd.read_excel('https://covid.ourworldindata.org/data/owid-covid-data.xlsx')

covid.head()

#3 Explore and clean the data by: (20 pt)
# The Netherlands total deaths with other Western Countrys and there total vaccinated peoples.
covid.loc[covid.Pclass == 1, ['The Netherlands']















#3 Explore and clean the data by:

#4 Describe and visualise: (50 pt)

#5 Conclusion (5pt)